---
- name: rds security group
  ec2_group:
    description: "database security group for {{environment_region}}"
    name: "{{rds_security_group}}"
    region: "{{region}}"
    vpc_id: "{{vpc_id}}"
    state: present
    rules:
      - proto: tcp
        from_port: 5432
        to_port: 5432
        cidr_ip: "{{vpc_subnet}}"
      - proto: tcp
        from_port: 5432
        to_port: 5432
        group_name: "{{coreos_vpn_security_group}}"
  register: rds_security_group_result

- name: rds subnet group
  rds_subnet_group:
    description: rds subnet group for {{environment_region}}
    name: rds {{environment_region}}
    region: "{{region}}"
    state: present
    subnets: "{{availability_zones|dict_values|map(attribute='subnet_id')|list}}"

- name: rds instances
  rds:
    command: create
    db_engine: "{{item.db_engine}}"
    db_name: "{{item.db_name}}"
    instance_name: "{{item.db_name}}"
    instance_type: "{{item.instance_type}}"
    multi_zone: "{{item.multi_zone}}"
    password: "{{database_passwords[opseeenv][item.db_name]}}"
    publicly_accessible: no
    region: "{{region}}"
    vpc_security_groups: "{{rds_security_group_result.group_id}}"
    size: "{{item.size}}"
    username: "{{item.username}}"
    subnet: rds {{environment_region}}
    tags:
      Environment: "{{opseeenv}}"
  with_items: rds_instances
