---
- name: register task definitions
  ecs_task_definition:
    region: "{{region}}"
    family: "{{item.family}}"
    definitions: "{{item.containerDefinitions}}"
    volumes: "{{item.volumes|default([])}}"
  with_items: ecs_tasks
