# region info
region: us-west-2
vpc_id: vpc-b5f3a4d0
vpc_subnet: "172.30.0.0/16"
internet_gateway_id: igw-8e76e7eb
route_table_id: rtb-f0085195
availability_zones:
  us-west-2a:
    subnet_id: subnet-50760c27
    cidr: "172.30.0.0/20"
    name: us-west-2a
  us-west-2b:
    subnet_id: subnet-58f9dd3d
    cidr: "172.30.16.0/20"
    name: us-west-2b
  us-west-2c:
    subnet_id: subnet-b233aeeb
    cidr: "172.30.32.0/20"
    name: us-west-2c
server_certificate_ids:
  opsy_co: arn:aws:iam::933693344490:server-certificate/OpsyCoWildcard
  opsee_co: arn:aws:iam::933693344490:server-certificate/OpseeCoWildcard
  opsee_com: arn:aws:iam::933693344490:server-certificate/cloudfront/OpseeComWildcard

# strongswan vpn
strongswan_gateway_name: "{{region}}.vpn.opsee.com"
strongswan_gateway_ip: "{{availability_zones['us-west-2a'].cidr | ipsubnet(24, 0) | ipaddr(-1) | ipaddr('address') }}"
strongswan_gateway_subnet: "{{vpc_subnet}}"
strongswan_client_subnet: "10.100.255.0/24"
strongswan_security_group: "strongSwan {{region}}"
strongswan_instance_type: t2.micro
strongswan_keypair: "strongSwan keypair {{region}}"
strongswan_public_ip: "52.26.106.239"
strongswan_instance_subnet_id: "{{availability_zones['us-west-2a'].subnet_id}}"
strongswan_instance_profile: CoreOS_Cluster_Role

# ecs cluster
ecs_cluster_name: "{{environment}}"

# coreos cluster
coreos_security_group: "CoreOS cluster {{region}}"
coreos_vpn_security_group: "{{strongswan_security_group}}"
coreos_ssh_elb_security_group: "CoreOS cluster ssh ELB {{region}}"
coreos_internal_elb_security_group: "CoreOS cluster internal ELB {{region}}"
coreos_public_elb_security_group: "CoreOS cluster public ELB {{region}}"
coreos_keypair: "CoreOS cluster keypair {{region}}"
coreos_instance_profile: CoreOS_Cluster_Role
coreos_ami: ami-ed8b90dd
coreos_master_instance_type: t2.micro
coreos_worker_instance_type: m4.large
coreos_master_deployment:
  - availability_zone: "{{availability_zones['us-west-2a']}}"
    private_ip: "{{availability_zones['us-west-2a'].cidr | ipsubnet(24, 1) | ipaddr(1) | ipaddr('address')}}"
  - availability_zone: "{{availability_zones['us-west-2b']}}"
    private_ip: "{{availability_zones['us-west-2b'].cidr | ipsubnet(24, 1) | ipaddr(1) | ipaddr('address')}}"
  - availability_zone: "{{availability_zones['us-west-2c']}}"
    private_ip: "{{availability_zones['us-west-2c'].cidr | ipsubnet(24, 1) | ipaddr(1) | ipaddr('address')}}"
coreos_worker_deployment:
  - availability_zone: "{{availability_zones['us-west-2a']}}"
  - availability_zone: "{{availability_zones['us-west-2b']}}"

# databases
rds_security_group: "RDS {{region}}"
rds_instances:
  fieri:
    db_engine: postgres
    db_name: fieri
    instance_type: db.m3.medium
    multi_zone: no
    size: 100
    username: fieri
  vape:
    db_engine: postgres
    db_name: vape
    instance_type: db.m3.medium
    multi_zone: no
    size: 100
    username: vape
  bartnet:
    db_engine: postgres
    db_name: bartnet
    instance_type: db.m3.medium
    multi_zone: no
    size: 100
    username: bartnet
  beavis:
    db_engine: postgres
    db_name: beavis
    instance_type: db.m3.medium
    multi_zone: no
    size: 100
    username: beavis

# load balancers
elb_load_balancers:
  etcd:
    name: etcd
    health_check:
      ping_protocol: http
      ping_port: 2379
      ping_path: "/health"
      response_timeout: 2
      interval: 5
      unhealthy_threshold: 2
      healthy_threshold: 5
    listeners:
      - protocol: https
        load_balancer_port: 443
        instance_port: 2379
        ssl_certificate_id: "{{server_certificate_ids.opsy_co}}"
    security_groups:
      - "{{coreos_internal_elb_security_group}}"
  fieri:
    name: fieri
    health_check:
      ping_protocol: http
      ping_port: 9092
      ping_path: "/health"
      response_timeout: 2
      interval: 5
      unhealthy_threshold: 2
      healthy_threshold: 5
    listeners:
      - protocol: https
        load_balancer_port: 443
        instance_port: 9092
        ssl_certificate_id: "{{server_certificate_ids.opsy_co}}"
    security_groups:
      - "{{coreos_internal_elb_security_group}}"
  vape_private:
    name: vape-private
    health_check:
      ping_protocol: http
      ping_port: 9091
      ping_path: "/health"
      response_timeout: 2
      interval: 5
      unhealthy_threshold: 2
      healthy_threshold: 5
    listeners:
      - protocol: https
        load_balancer_port: 443
        instance_port: 9091
        ssl_certificate_id: "{{server_certificate_ids.opsy_co}}"
    security_groups:
      - "{{coreos_internal_elb_security_group}}"
  beavis:
    name: beavis
    health_check:
      ping_protocol: http
      ping_port: 2020
      ping_path: "/health_check"
      response_timeout: 2
      interval: 5
      unhealthy_threshold: 2
      healthy_threshold: 5
    listeners:
      - protocol: https
        load_balancer_port: 443
        instance_port: 2020
        ssl_certificate_id: "{{server_certificate_ids.opsy_co}}"
    security_groups:
      - "{{coreos_internal_elb_security_group}}"
  bartnet:
    name: bartnet
    health_check:
      ping_protocol: http
      ping_port: 8080
      ping_path: "/health_check"
      response_timeout: 2
      interval: 5
      unhealthy_threshold: 2
      healthy_threshold: 5
    listeners:
      - protocol: https
        load_balancer_port: 443
        instance_port: 8080
        ssl_certificate_id: "{{server_certificate_ids.opsy_co}}"
    security_groups:
      - "{{coreos_internal_elb_security_group}}"
  nsqd:
    name: nsqd
    health_check:
      ping_protocol: tcp
      ping_port: 4150
      response_timeout: 2
      interval: 5
      unhealthy_threshold: 2
      healthy_threshold: 5
    listeners:
      - protocol: tcp
        load_balancer_port: 4150
        instance_port: 4150
      - protocol: http
        load_balancer_port: 4151
        instance_port: 4151
    security_groups:
      - "{{coreos_internal_elb_security_group}}"
  nsqadmin:
    name: nsqadmin
    health_check:
      ping_protocol: http
      ping_port: 4171
      ping_path: "/"
      response_timeout: 2
      interval: 5
      unhealthy_threshold: 2
      healthy_threshold: 5
    listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 4171
    security_groups:
      - "{{coreos_internal_elb_security_group}}"
  emissary:
    name: emissary
    health_check:
      ping_protocol: http
      ping_port: 80
      ping_path: "/index.html"
      response_timeout: 2
      interval: 5
      unhealthy_threshold: 2
      healthy_threshold: 5
    listeners:
      - protocol: https
        load_balancer_port: 443
        instance_port: 80
        ssl_certificate_id: "{{server_certificate_ids.opsee_com}}"
    security_groups:
      - "{{coreos_public_elb_security_group}}"
    scheme: internet-facing
  vape_public:
    name: vape-public
    health_check:
      ping_protocol: http
      ping_port: 8081
      ping_path: "/health"
      response_timeout: 2
      interval: 5
      unhealthy_threshold: 2
      healthy_threshold: 5
    listeners:
      - protocol: https
        load_balancer_port: 443
        instance_port: 8081
        ssl_certificate_id: "{{server_certificate_ids.opsee_com}}"
    security_groups:
      - "{{coreos_public_elb_security_group}}"
    scheme: internet-facing
  motorn:
    name: motorn
    health_check:
      ping_protocol: http
      ping_port: 8083
      ping_path: "/health"
      response_timeout: 2
      interval: 5
      unhealthy_threshold: 2
      healthy_threshold: 5
    listeners:
      - protocol: https
        load_balancer_port: 443
        instance_port: 8083
        ssl_certificate_id: "{{server_certificate_ids.opsee_com}}"
    security_groups:
      - "{{coreos_public_elb_security_group}}"
    scheme: internet-facing
