# region info
region: us-west-2
vpc_id: vpc-b5f3a4d0
vpc_subnet: "172.30.0.0/16"
internet_gateway_id: igw-8e76e7eb
route_table_id: rtb-f0085195
availability_zones:
  us-west-2a:
    subnet_id: subnet-50760c27
    cidr: "172.30.0.0/20"
    name: us-west-2a
  us-west-2b:
    subnet_id: subnet-58f9dd3d
    cidr: "172.30.16.0/20"
    name: us-west-2b
  us-west-2c:
    subnet_id: subnet-b233aeeb
    cidr: "172.30.32.0/20"
    name: us-west-2c

# strongswan vpn
strongswan_gateway_name: "{{region}}.vpn.opsee.com"
strongswan_gateway_ip: "{{availability_zones['us-west-2a'].cidr | ipsubnet(24, 0) | ipaddr(-1) | ipaddr('address') }}"
strongswan_gateway_subnet: "{{vpc_subnet}}"
strongswan_client_subnet: "10.100.255.0/24"
strongswan_security_group: "strongSwan {{region}}"
strongswan_instance_type: t2.micro
strongswan_keypair: "strongSwan keypair {{region}}"
strongswan_public_ip: "52.26.106.239"
strongswan_instance_subnet_id: "{{availability_zones['us-west-2a'].subnet_id}}"
strongswan_instance_profile: CoreOS_Cluster_Role

# ecs cluster
ecs_cluster_name: "{{environment}}"

# coreos cluster
coreos_security_group: "CoreOS cluster {{region}}"
coreos_vpn_security_group: "{{strongswan_security_group}}"
coreos_ssh_elb_security_group: "CoreOS cluster ssh ELB {{region}}"
coreos_internal_elb_security_group: "CoreOS cluster internal ELB {{region}}"
coreos_keypair: "CoreOS cluster keypair {{region}}"
coreos_instance_profile: CoreOS_Cluster_Role
coreos_ami: ami-ed8b90dd
coreos_master_instance_type: t2.micro
coreos_worker_instance_type: m4.large
coreos_master_deployment:
  - availability_zone: "{{availability_zones['us-west-2a']}}"
    private_ip: "{{availability_zones['us-west-2a'].cidr | ipsubnet(24, 1) | ipaddr(1) | ipaddr('address')}}"
  - availability_zone: "{{availability_zones['us-west-2b']}}"
    private_ip: "{{availability_zones['us-west-2b'].cidr | ipsubnet(24, 1) | ipaddr(1) | ipaddr('address')}}"
  - availability_zone: "{{availability_zones['us-west-2c']}}"
    private_ip: "{{availability_zones['us-west-2c'].cidr | ipsubnet(24, 1) | ipaddr(1) | ipaddr('address')}}"
coreos_worker_deployment:
  - availability_zone: "{{availability_zones['us-west-2a']}}"
  - availability_zone: "{{availability_zones['us-west-2b']}}"
