#cloud-config
coreos:
  fleet:
    metadata: "role=node"
  units:
    - name: etcd.service
      command: stop
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start
      drop-ins:
        - name: 30-listen-stream.conf
          content: |
            [Socket]
            ListenStream="127.0.0.1:49153"
    - name: docker-tcp.socket
      command: start
      enable: true
      content: |
        [Unit]
        Description=Docker Socket for Remote API
        
        [Socket]
        ListenStream=2376
        BindIPv6Only=both
        Service=docker.service
        
        [Install]
        WantedBy=sockets.target
    - name: docker.service
      command: start
    - name: Users.mount
      command: start
      content: |
        [Mount]
        What=192.168.64.1:/Users
        Where=/Users
        Type=nfs
  update:
    group: beta
    reboot-strategy: etcd-lock
write_files:
  - path: /opt/etc/environment
    permissions: 0644
    owner: root
    content: |
      ETCD_HOST=$private_ipv4
      ETCD_PORT=2379
