---
- hosts: localhost
  connection: local
  vars:
    ecs_tasks: []
    ecs_services: []
    ecs_image_tag: "{{lookup('env', 'IMAGE_TAG')}}"

  vars_files:
    - ../environments/{{opseeenv}}.yml

  pre_tasks:
    - include: opsee-services-loader.yml

    - name: ensure image tag is specified
      fail: msg="You must specify a versioned container image tag."
      when: ecs_image_tag == "" or ecs_image_tag == "latest"

    - name: set ecs tasks
      set_fact:
        ecs_tasks: "{{ecs_tasks + item.value.tasks}}"
      with_dict: opsee_services
      when: item.value.tasks is defined

    - name: set ecs services
      set_fact:
        ecs_services: "{{ecs_services + item.value.services}}"
      with_dict: opsee_services
      when: item.value.services is defined

  roles:
    - role: ecs
      ecs_register_tasks: yes
      ecs_create_services: yes

  tasks:
    - name: notify
      slack:
        token: "T03B4DP5B/B0DMRBAHK/FqfU5SVMzINL9GCvNBhRQXoz"
        color: good
        icon_url: "https://s3-us-west-1.amazonaws.com/opsee-public-images/slack-avi-48-green.png"
        msg: "I just deployed {{item.key}} -- cool cool."
        username: DeployBot
      with_dict: opsee_services
      tags: notify
