---
- hosts: localhost
  connection: local
  vars:
    ecs_tasks: []
    ecs_services: []
    ecs_image_tag: "{{lookup('env', 'IMAGE_TAG')}}"

  vars_files:
    - ../environments/{{environment}}.yml

  pre_tasks:
    - include: opsee-services-loader.yml

    - name: set the image tag
      set_fact:
        ecs_image_tag: latest
      when: ecs_image_tag == ""

    - name: set ecs tasks
      set_fact:
        ecs_tasks: "{{ecs_tasks + item.value.tasks}}"
      with_dict: opsee_services
      when: item.value.tasks is defined

    - name: set ecs services
      set_fact:
        ecs_services: "{{ecs_services + item.value.services}}"
      with_dict: opsee_services
      when: item.value.services is defined

  roles:
    - role: ecs
      ecs_register_tasks: yes
      ecs_create_services: yes
